### ISSUE TITLE
Add support for functions

### ISSUE THREAD

**Issue by bohnman** [bohnman/squiggly-java#19]
Add support for calling functions on field names/values

Example:

issue.actions.limit(5)[type]  -> select the first 5 elements of the actions list, only selecting their type field

Some functions could be
- limit
- range
- replace
- sort

There would be some capability for registration of custom functions

**Comment by passionate-developer** [comment]
great, please let us know when it can be ready. it will be extremely helpful :)

**Comment by bohnman** [comment]
The development for this has been completed and will be available in the 2.0 release

**Comment by passionate-developer** [comment]
Thanks.  When will 2.0 be released?

**Comment by bohnman** [comment]
2.0 is almost feature complete.  Then, it's javadocs, unit tests, and documentation until my eyes glaze over.  Hopefully, in a week or so.  I know I  keep saying that!

**Comment by bohnman** [comment]
I'm going to try to aim to get it done in September, hopefully earlier!

**Comment by xak2000** [comment]
These estimate looks really funny in retrospective. :-)

But I understand you really well! I'm "master of the estimation" too! ))
