### ISSUE TITLE
How to excluding nested fields?

### ISSUE THREAD

**Issue by yinwerhong** [bohnman/squiggly-java#38]
I got result object in json:

`{"code":"000000","data":{"createdAt":1519459033000,"id":1,"class":"fullpath.user.dto.UserDto","username":"test"},"message":"SUCCESS","class":"fullpath.result.Result"}`

I want to ignore class fields, then I found your awesome library in this way:

`SquigglyUtils.stringify(Squiggly.init(objectMapper, "-class"), result);`

then I got it in this (class field of outer layer was ignored):
`{"code":"000000","data":{"createdAt":1519459033000,"id":1,"class":"fullpath.user.dto.UserDto","username":"test"},"message":"SUCCESS"}`

How can I figure out result object in below format? Thanks in advance.
{"code":"000000","data":{"createdAt":1519459033000,"id":1,"username":"test"},"message":"SUCCESS"}

**Comment by bohnman** [comment]
Filters currently are not recursive (hoping to add this in version 2).

I think the following should work

``**,-class,data[-class]``

**Comment by yinwerhong** [comment]
Thanks very much, it works very well, glad to see the futures in version 2.

**Comment by XQDD** [comment]
Any update for this(recursive filter)?
