### ISSUE TITLE
Does squiggly support json path expression filter? Its good to have the standard way of filtering. Any comments?

### ISSUE THREAD

**Issue by Visanth** [bohnman/squiggly-java#45]

**Comment by bohnman** [comment]
No, Squiggly does not support json path expression filter.  Squiggly was inspired by the filtering syntax in the [Facebook Graph API](https://developers.facebook.com/docs/graph-api/using-graph-api).  There are no plans to support the json path expression filter.

I actually disagree with the premise "It's good to have the standard way of filtering":

- standards stifle innovation.  If I follow a standard then I am limited by that standard.  Json path is very limiting, especially with regard to version 2 of Squiggly, which is in development.
- Unlike XPath, JsonPath is not a standard.  It does not have a specification and was not approved by a committee.  Is it used by more people than Squiggly? yes   Has it been around longer than Squiggly? yes  But, then these are also true of the Facebook Graph API.

Standards are great when developing new protocols or a new language.  They're not that great when we're talking about a small GitHub library.
