### ISSUE TITLE
squiggly-java not recognized after deploy war file tomcat

### ISSUE THREAD

**Issue by damascenol** [bohnman/squiggly-java#53]
Hi,

When I use squiggly on development environment with embebed tomcat work as expected filtering fields. but when I build the war-file and add to external tomcat its not recognized and throw infinite recursion. Anyone know how to fix this?

- squiggly version: 1.3.14
- spring boot: 1.5.2

Tomcat 7 Java 8

Thank you

**Comment by bohnman** [comment]
@damascenol Please take at look at examples/servlet.  Run ```mvn package``` and then unjar the squiggly.war to the ROOT webapp directory of your Tomcat instance .  Then follow the README.md in that directory to make curl requests to test it out.  You can also test in the browser, but remember to url encode the square brackets in the fields query parameter.

If you are still having trouble, please attach a war exhibiting the problem with instructions how to replicate.

Thanks!

~Ryan

**Comment by damascenol** [comment]
Thanks, I can make it work now!

This is a great library.
