### ISSUE TITLE
Adding fields to baseview

### ISSUE THREAD

**Issue by cmercer** [bohnman/squiggly-java#66]
I have a defined baseview that works well as defaults but I have situations where the requester wants to add a few fields.  There doesn't seem to be a good way to do that.

```
/orders?fields=customer
```
Means that only customer gets returned.  What I am looking for is to dynamically add to the baseview with something like this.
```
/orders?fields=+customer
```
It might be functionality already there and I am missing it.

**Comment by cmercer** [comment]
after looking at this more I was missing it.  
```
/orders?fields=base,customer
```

**Comment by bohnman** [comment]
You be able to do the following:

```
/orders?fields=base,customer 
```

**Comment by cmercer** [comment]
Thanks I found it it right as you commented.
